version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
  app:
    image: node:16
    working_dir: /src
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./:/src
    command: sh -c "npx nodemon --legacy-watch -r dotenv/config src/app.js"
